import type { Metadata } from "next";
import { Baloo_Bhai_2 } from "next/font/google";
import "./ui/globals.css";
import MenuNavigation from "@/components/ui/menu-navigation";
/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
 */
const baloo = Baloo_Bhai_2({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${baloo.className} antialiased flex`}>
        <section className="w-[15%] ">
          <MenuNavigation />
        </section>
        {children}
      </body>
    </html>
  );
}
